---
- name: Stop dhcpcd
  service:
    name: dhcpcd
    state: stopped
    enabled: no

- name: Add gateman host entry
  lineinfile:
    path: /etc/hosts
    line: "192.168.3.1 gmh"
    owner: root
    group: root

- name: Install apt packages
  apt:
    pkg:
      - dnsmasq
      - hostapd
      - python-backports.ssl-match-hostname

- name: Configure dnsmasq
  copy:
    dest: /etc/dnsmasq.conf
    content: |
      interface=br0
      dhcp-range=192.168.2.2,192.168.2.20,24h
      interface=eth0
      dhcp-range=192.168.3.2,192.168.3.20,24h
      interface=wlan0
      dhcp-range=192.168.4.2,192.168.4.20,24h

- name: Enable dnsmasq
  systemd:
    name: dnsmasq
    state: started
    enabled: yes

- name: Configure hostapd
  copy:
    dest: /etc/hostapd/hostapd.conf
    content: |
      interface=wlan0
      driver=nl80211
      ssid=xr-cloud
      hw_mode=g
      channel=7
      wpa=2
      wpa_passphrase=gatemann
      wpa_key_mgmt=WPA-PSK
      wpa_pairwise=TKIP

- name: Enable hostapd
  systemd:
    name: hostapd
    state: started
    masked: no
    enabled: yes

- name: Static IP to eth0
  template:
    src: "{{ role_path }}/files/eth0.j2"
    dest: /etc/network/interfaces.d/eth0

- name: Static IP to wlan0
  template:
    src: "{{ role_path }}/files/wlan0.j2"
    dest: /etc/network/interfaces.d/wlan0
